# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=120, verbose_name='photo')),
                ('name_prefix', models.CharField(blank=True, max_length=30, null=True, verbose_name='name prefix')),
                ('first_name', models.CharField(max_length=15, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('name_suffix', models.CharField(blank=True, max_length=30, null=True, verbose_name='name suffix')),
                ('nicknames', models.CharField(blank=True, max_length=120, null=True, verbose_name='nicknames')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'contact',
            },
        ),
    ]
