#coding=UTF-8


SIZES = (
    (u'XS', u'Extra Small'),
    (u'S', u'Small'),
    (u'M', u'Medium'),
    (u'L', u'Large'),
    (u'XL', u'Extra Large'),
)

DAYS = (
    (1, u'Monday'),
    (2, u'Tuesday'),
    (3, u'Wednesday'),
    (4, u'Thursday'),
    (5, u'Friday'),
    (6, u'Saturday'),
    (7, u'Sunday'),
)

COUNTRIES = (
    (u'AF', u'Afganistán'),
    (u'AX', u'Åland'),
    (u'AL', u'Albania'),
    (u'DE', u'Alemania'),
    (u'AD', u'Andorra'),
    (u'AO', u'Angola'),
    (u'AI', u'Anguila'),
    (u'AQ', u'Antártida'),
    (u'AG', u'Antigua y Barbuda'),
    (u'AN', u'Antillas Neerlandesas'),
    (u'SA', u'Arabia Saudita'),
    (u'DZ', u'Argelia'),
    (u'AR', u'Argentina'),
    (u'AM', u'Armenia'),
    (u'AW', u'Aruba'),
    (u'AU', u'Australia'),
    (u'AT', u'Austria'),
    (u'AZ', u'Azerbaiyán'),
    (u'BS', u'Bahamas'),
    (u'BH', u'Bahréin'),
    (u'BD', u'Bangladesh'),
    (u'BB', u'Barbados'),
    (u'BE', u'Bélgica'),
    (u'BZ', u'Belice'),
    (u'BJ', u'Benín'),
    (u'BM', u'Bermudas'),
    (u'BY', u'Bielorrusia'),
    (u'MM', u'Birmania'),
    (u'BO', u'Bolivia'),
    (u'BA', u'Bosnia y Herzegovina'),
    (u'BW', u'Botsuana'),
    (u'BV', u'Isla Bouvet'),
    (u'BR', u'Brasil'),
    (u'BN', u'Brunéi'),
    (u'BG', u'Bulgaria'),
    (u'BF', u'Burkina Faso'),
    (u'BI', u'Burundi'),
    (u'BT', u'Bután'),
    (u'CV', u'Cabo Verde'),
    (u'KY', u'Islas Caimán'),
    (u'KH', u'Camboya'),
    (u'CM', u'Camerún'),
    (u'CA', u'Canadá'),
    (u'CF', u'República Centroafricana'),
    (u'TD', u'Chad'),
    (u'CZ', u'República Checa'),
    (u'CL', u'Chile'),
    (u'CN', u'China'),
    (u'CY', u'Chipre'),
    (u'CC', u'Islas Cocos'),
    (u'CO', u'Colombia'),
    (u'KM', u'Comoras'),
    (u'CG', u'República del Congo'),
    (u'CD', u'República Democrática del Congo'),
    (u'CK', u'Islas Cook'),
    (u'KP', u'Corea del Norte'),
    (u'KR', u'Corea del Sur'),
    (u'CI', u'Costa de Marfil'),
    (u'CR', u'Costa Rica'),
    (u'HR', u'Croacia'),
    (u'CU', u'Cuba'),
    (u'DK', u'Dinamarca'),
    (u'DM', u'Dominica'),
    (u'DO', u'República Dominicana'),
    (u'EC', u'Ecuador'),
    (u'EG', u'Egipto'),
    (u'SV', u'El Salvador'),
    (u'AE', u'Emiratos Árabes Unidos'),
    (u'ER', u'Eritrea'),
    (u'SK', u'Eslovaquia'),
    (u'SI', u'Eslovenia'),
    (u'ES', u'España'),
    (u'US', u'Estados Unidos'),
    (u'UM', u'Islas ultramarinas de Estados Unidos'),
    (u'EE', u'Estonia'),
    (u'ET', u'Etiopía'),
    (u'FO', u'Islas Feroe'),
    (u'PH', u'Filipinas'),
    (u'FI', u'Finlandia'),
    (u'FJ', u'Fiyi'),
    (u'FR', u'Francia'),
    (u'GA', u'Gabón'),
    (u'GM', u'Gambia'),
    (u'GE', u'Georgia'),
    (u'GS', u'Islas Georgias del Sur y Sandwich del Sur'),
    (u'GH', u'Ghana'),
    (u'GI', u'Gibraltar'),
    (u'GD', u'Granada'),
    (u'GR', u'Grecia'),
    (u'GL', u'Groenlandia'),
    (u'GP', u'Guadalupe'),
    (u'GU', u'Guam'),
    (u'GT', u'Guatemala'),
    (u'GF', u'Guayana Francesa'),
    (u'GG', u'Guernsey'),
    (u'GN', u'Guinea'),
    (u'GQ', u'Guinea Ecuatorial'),
    (u'GW', u'Guinea-Bissau'),
    (u'GY', u'Guyana'),
    (u'HT', u'Haití'),
    (u'HM', u'Islas Heard y McDonald'),
    (u'HN', u'Honduras'),
    (u'HK', u'Hong Kong'),
    (u'HU', u'Hungría'),
    (u'IN', u'India'),
    (u'ID', u'Indonesia'),
    (u'IR', u'Irán'),
    (u'IQ', u'Iraq'),
    (u'IE', u'Irlanda'),
    (u'IS', u'Islandia'),
    (u'IL', u'Israel'),
    (u'IT', u'Italia'),
    (u'JM', u'Jamaica'),
    (u'JP', u'Japón'),
    (u'JE', u'Jersey'),
    (u'JO', u'Jordania'),
    (u'KZ', u'Kazajistán'),
    (u'KE', u'Kenia'),
    (u'KG', u'Kirguistán'),
    (u'KI', u'Kiribati'),
    (u'KW', u'Kuwait'),
    (u'LA', u'Laos'),
    (u'LS', u'Lesoto'),
    (u'LV', u'Letonia'),
    (u'LB', u'Líbano'),
    (u'LR', u'Liberia'),
    (u'LY', u'Libia'),
    (u'LI', u'Liechtenstein'),
    (u'LT', u'Lituania'),
    (u'LU', u'Luxemburgo'),
    (u'MO', u'Macao'),
    (u'MK', u'República de Macedonia'),
    (u'MG', u'Madagascar'),
    (u'MY', u'Malasia'),
    (u'MW', u'Malaui'),
    (u'MV', u'Maldivas'),
    (u'ML', u'Malí'),
    (u'MT', u'Malta'),
    (u'FK', u'Islas Malvinas'),
    (u'IM', u'Isla de Man'),
    (u'MP', u'Islas Marianas del Norte'),
    (u'MA', u'Marruecos'),
    (u'MH', u'Islas Marshall'),
    (u'MQ', u'Martinica'),
    (u'MU', u'Mauricio'),
    (u'MR', u'Mauritania'),
    (u'YT', u'Mayotte'),
    (u'MX', u'México'),
    (u'FM', u'Micronesia'),
    (u'MD', u'Moldavia'),
    (u'MC', u'Mónaco'),
    (u'MN', u'Mongolia'),
    (u'ME', u'Montenegro'),
    (u'MS', u'Montserrat'),
    (u'MZ', u'Mozambique'),
    (u'NA', u'Namibia'),
    (u'NR', u'Nauru'),
    (u'CX', u'Isla de Navidad'),
    (u'NP', u'Nepal'),
    (u'NI', u'Nicaragua'),
    (u'NE', u'Níger'),
    (u'NG', u'Nigeria'),
    (u'NU', u'Niue'),
    (u'NF', u'Norfolk'),
    (u'NO', u'Noruega'),
    (u'NC', u'Nueva Caledonia'),
    (u'NZ', u'Nueva Zelanda'),
    (u'OM', u'Omán'),
    (u'NL', u'Países Bajos'),
    (u'PK', u'Pakistán'),
    (u'PW', u'Palaos'),
    (u'PS', u'Territorios palestinos'),
    (u'PA', u'Panamá'),
    (u'PG', u'Papúa Nueva Guinea'),
    (u'PY', u'Paraguay'),
    (u'PE', u'Perú'),
    (u'PN', u'Islas Pitcairn'),
    (u'PF', u'Polinesia Francesa'),
    (u'PL', u'Polonia'),
    (u'PT', u'Portugal'),
    (u'PR', u'Puerto Rico'),
    (u'QA', u'Qatar'),
    (u'GB', u'Reino Unido'),
    (u'RE', u'Reunión'),
    (u'RW', u'Ruanda'),
    (u'RO', u'Rumania'),
    (u'RU', u'Rusia'),
    (u'EH', u'República Árabe Saharaui Democrática'),
    (u'SB', u'Islas Salomón'),
    (u'WS', u'Samoa'),
    (u'AS', u'Samoa Americana'),
    (u'BL', u'San Bartolomé'),
    (u'KN', u'San Cristóbal y Nieves'),
    (u'SM', u'San Marino'),
    (u'MF', u'San Martín'),
    (u'PM', u'San Pedro y Miquelón'),
    (u'VC', u'San Vicente y las Granadinas'),
    (u'SH', u'Santa Helena'),
    (u'LC', u'Santa Lucía'),
    (u'ST', u'Santo Tomé y Príncipe'),
    (u'SN', u'Senegal'),
    (u'RS', u'Serbia'),
    (u'SC', u'Seychelles'),
    (u'SL', u'Sierra Leona'),
    (u'SG', u'Singapur'),
    (u'SY', u'Siria'),
    (u'SO', u'Somalia'),
    (u'LK', u'Sri Lanka'),
    (u'SZ', u'Suazilandia'),
    (u'ZA', u'Sudáfrica'),
    (u'SD', u'Sudán'),
    (u'SE', u'Suecia'),
    (u'CH', u'Suiza'),
    (u'SR', u'Surinam'),
    (u'SJ', u'Svalbard y Jan Mayen'),
    (u'TH', u'Tailandia'),
    (u'TW', u'Taiwán'),
    (u'TZ', u'Tanzania'),
    (u'TJ', u'Tayikistán'),
    (u'IO', u'Territorio Británico del Océano Índico'),
    (u'TF', u'Territorios Australes Franceses'),
    (u'TL', u'Timor Oriental'),
    (u'TG', u'Togo'),
    (u'TK', u'Tokelau'),
    (u'TO', u'Tonga'),
    (u'TT', u'Trinidad y Tobago'),
    (u'TN', u'Túnez'),
    (u'TC', u'Islas Turcas y Caicos'),
    (u'TM', u'Turkmenistán'),
    (u'TR', u'Turquía'),
    (u'TV', u'Tuvalu'),
    (u'UA', u'Ucrania'),
    (u'UG', u'Uganda'),
    (u'UY', u'Uruguay'),
    (u'UZ', u'Uzbekistán'),
    (u'VU', u'Vanuatu'),
    (u'VA', u'Ciudad del Vaticano'),
    (u'VE', u'Venezuela'),
    (u'VN', u'Vietnam'),
    (u'VG', u'Islas Vírgenes Británicas'),
    (u'VI', u'Islas Vírgenes de los Estados Unidos'),
    (u'WF', u'Wallis y Futuna'),
    (u'YE', u'Yemen'),
    (u'DJ', u'Yibuti'),
    (u'ZM', u'Zambia'),
    (u'ZW', u'Zimbabue'),
)